python main_pl.py \
    --project DeiT-PL \
    --name deit_base_patch16_224 \
    --model deit_base_patch16_224 \
    --accelerator npu \
    --batch-size 256 \
    --precision 16 \
    --log_every_n_steps 1 \
    --lr_monitor.logging_interval epoch \
    --model_checkpoint.dirpath ckpt \
    --model_checkpoint.save_weights_only True \
    --data-path /home/ma-user/work/wenzhuoliu/torch_ds/imagenet
